version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  # # create summary table
  calculate_summary_table:
    run: r:latest analysis/calc_summary_tab.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure_csv: output/summary_table.csv